name: Déployer le site Jekyll sur GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le workflow lors des pushs sur la branche main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3

    # Configuration Ruby et Bundler
    - name: Configurer Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Version Ruby dans votre Gemfile
        bundler-cache: false # Désactive la mise en cache pour éviter les conflits

    - name: Installer la version correcte de Bundler
      run: |
        gem install bundler -v 2.5.23  # Installe la version compatible
        bundle _2.5.23_ install       # Forcer cette version pour l'installation des gems

    # Configuration Node.js et npm
    - name: Configurer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Mettre à jour npm
      run: npm install -g npm@11.0.0  # Met à jour npm vers la version 11.0.0 compatible

    - name: Installer les dépendances NPM
      run: npm install

    - name: Compiler SCSS en CSS
      run: npm run build-css

    # Construire le site Jekyll
    - name: Construire le site Jekyll
      run: bundle exec jekyll build

    # Déployer sur GitHub Pages
    - name: Déployer sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site # Dossier de sortie Jekyll
